language: node_js
node_js:
  - "12.6"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run lint
  - ng test --watch=false
  - ng build --prod --base-href https://sundareshwarankannan.github.io/bookmark-ui/

after_success:
  - cat ./coverage/bookmark-ui/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on:
